### PR TITLE
Vivo UI styled card wrapper

### PR DESCRIPTION
**Pull request by nicolasparada**
Wrapped Vivo UI in a styled card container.

Also improved includes filter to covert other types to string to do the matching; for example the number `92` in a log now can be matched using the filter `"92"`.

Screen Shot 2022-10-24 at 15 18 48
Screen Shot 2022-10-24 at 15 18 53

### CODE REVIEW

**Comment by edsiper** [comment]
can you move these buttons to the right and add some space between them ?

**Comment by nicolasparada** [comment]
@edsiper I cannot see your screenshot. I just pushed a new commit tho changing it a little bit.
Can you tell me again after you pull the latest commit and rebuild the extension?

**Comment by nicolasparada** [comment]
Screen Shot 2022-10-24 at 15 23 07

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
