### PR TITLE
vivo: Implement filtering

### PR DESCRIPTION
**Pull request by tarruda**
This implements a simple form of filtering concept though a json query language. We can improve upon this later by creating a parser which creates a proper query language into an AST (right now only the AST is implemented)

Examples: 

```js
// filter records where the "log" key matches the regexp "12:20
{"key": "log", "matches": "12:20"}
// filter records where the "name" record equals "dummy"
{"key": "name", "equals": "dummy"}
// combine both filters above using an "or" operation
{"or": [{"key": "log", "matches": "12:20"}, {"key": "name", "equals": "dummy"}]}
```

cc @edsiper @agup006 

* update: As Eduardo suggested, I've implemented a simple filtering mechanism to search in all keys/values whatever is typed in the search box

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for opening this ticket, the feature looks pretty interesting.

One thing to consider heavily is "what's the query language to use for filtering ?". We have to use something that users understand or are familiar with beforehand. 

We could implement some kind of record accessor pattern + SQL like Fluent Bit or just a simplified version of PromQL. Right now Vivo supports logs, but we will expand to metrics and traces. 

For now, I suggest to implement a simple filter where the using can input any string like `abc` and that will try to match any key or value that contains that string.

**Comment by tarruda** [comment]
> For now, I suggest to implement a simple filter where the using can input any string like abc and that will try to match any key or value that contains that string.

Note that this could be implemented inside the current "language" as an operator like this: 

```json
{"or": [{"anyKeyMatches": "abc"}, { "anyValueMatches": "abc"}]}
```

The this "json query language" is very flexible, we can add whatever operators are needed. In the hypothetical example above, I've added two operators that when joined by "or" would result in "abc" being searched on every key/value of the record

**Comment by tarruda** [comment]
@edsiper I've implemented an "includes" operator like you suggested, but left the structure/code to implement a general query language later.

If you test the latest commit, the filter will match records that have any keys/values including the typed text

**Comment by tarruda** [comment]
@edsiper I just read the docs on fluent-bit SQL stream processing.

I added these filtering primitives because I didn't knew fluent-bit had support for a SQL-like language out of the box. I think you mentioned the first time you talked about filtering, but I didn't understand at the time.

It would be easy to modify Vivo to support passing whatever is in the filter textbox as the `-T` parameter to fluent-bit. Every time the query changes, we would automatically restart the backing fluent-bit.

I can do this after I get back from PTO next week

**Pull request merged**
